### ISSUE TITLE
YAML Configuration for M-Bus devices

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/mbusreader#5]
At  [CF Echo II Reading Discussion](https://github.com/ganehag/pyMeterBus/discussions/40)
@Thorsten1982  has successfully implemented reading from a CF Echo II heat meter. We should standardize this configuration using YAML files.

## Proposed Solution
Create three YAML configuration files:
* Device Configuration - see below
* IO Configuration see #7
* MQTT Configuration see #6 

```yaml
cf_echo_ii:
  model: CF Echo II
  manufacturer: Allmess/Itron
  baudrate: 2400
  wakeup:
    pattern: "0x55"
    times: 528
    delay: 0.350
    parity: even
  doc_url: https://www.allmess.de/fileadmin/multimedia/alle_Dateien/MA/MA_BA_12088-AC%20CF%20Echo%20II%20D%20TS1021_KL.pdf
  messages:
    read:
      command: "105BFE5916"
      expected_length: 620
    example_response: "684d4d680800722654832277040904360000000c78265483220406493500000c14490508000b2d0000000b3b0000000a5a18060a5e89020b61883200046d0d0c2c310227c80309fd0e2209fd0f470f00008d16"
```

## Tasks
- [x] Create device YAML schema
- [x] Document configuration structure
- [x] Implement example using @Thorsten1982's CF Echo II configuration
