### ISSUE TITLE
MQTT Integration for M-Bus Reader with YAML configuration

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/mbusreader#6]
Proposed YAML format

```yaml
mqtt:
  broker: localhost
  port: 1883
  username: ${MQTT_USER}
  password: ${MQTT_PASSWORD}
  topic_prefix: mbus
  publish:
    - topic: data
      format: json
      fields:
        - name: energy
          record: 0
        - name: volume
          record: 1
        - name: power
          record: 2
        - name: flow
          record: 3
  qos: 1
  retain: true
```

## Tasks
- [x] Create MQTT module
- [x] Define YAML configuration schema
- [ ] Add environment variable support
- [ ] Implement reconnection handling
- [ ] Add message transformation utilities
- [ ] Create examples using Home Assistant
