### ISSUE TITLE
YAML Configuration for IO devices

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/mbusreader#7]
Create minimal viable IO configuration:

```python
@lod_storable
class MBusIoConfig:
    """Configuration data class for M-Bus reader"""

    serial_device: str = "/dev/ttyUSB0"
    initial_baudrate: int = 2400
    timeout: float = 10.0
```
```yaml
serial_device: /dev/ttyUSB0
initial_baudrate: 2400
timeout: 10.0
```
